# Generated by Django 4.1 on 2022-08-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='email',
            field=models.EmailField(default='Null', max_length=100, verbose_name='Correo'),
            preserve_default=False,
        ),
    ]
